dict/urls.py
from django.urls import include, re_path
from . import views
app_name='dict'
urlpatterns = (
    re_path(r'^$', views.mainIndex, name='index'),
)

gonggo/urls.py
from django.urls import include, re_path
from . import views

app_name='gonggo'
urlpatterns = (
    re_path(r'^$', views.mainIndex, name='index'),

    re_path(r'^main/$', views.Indexmain, name='mainindex'),

     # 공고 게시물(id)의 세부 정보
    re_path(r'^([0-9]+)/$', views.gonggoDetail, name='detail'),

    # 공고 추가
    re_path(r'^add/$', views.gonggoAdd, name='add'),

    # 공고 수정
    re_path(r'^update/([0-9]+)/$', views.gonggoUpdate, name='update'),

    # 공고 삭제
    re_path(r'^delete/([0-9]+)/$', views.gonggoDelete, name='delete'),

    # 공고 폼
    re_path(r'^form/$', views.gonggoForm, name='form'),
    
)

main/urls.py
from django.urls import include, re_path
from . import views
app_name='main'
urlpatterns = (
    re_path(r'^$', views.mainIndex, name='index'),
)

myweb/urls.py
from django.urls import include, re_path, path
from django.contrib import admin
from myweb.views import mainIndex, regAccount, modiAccount, join1, join2, main, modi
from django.contrib.auth import views as auth_views



urlpatterns = [
    # 127.0.0.1:8000/
    re_path(r'^$', mainIndex, name='index'),

    # 127.0.0.1:8000/admin/...
    path('admin/', admin.site.urls),
    re_path(r'^account/register/$', regAccount, name='reg_account'),

    re_path(r'^account/modified/$', modiAccount, name='modi_account'),
    
    re_path(r'^account/register/join1/$', join1, name='join1'),

    re_path(r'^account/register/join2/$', join2, name='join2'),

    # 127.0.0.1:8000/board/...
    re_path(r'^board/', include(r'board.urls')),

    # 127.0.0.1:8000/news/...
    re_path(r'^news/', include(r'news.urls')),

    # 127.0.0.1:8000/webtoon/...
    re_path(r'^webtoon/', include(r'webtoon.urls')),

    # 127.0.0.1:8000/gonggo/...
    re_path(r'^gonggo/', include(r'gonggo.urls')),

    # /error/
    re_path(r'^error/', include(r'error.urls')),

    # 127.0.0.1:8000/modi/...
    re_path(r'^modi/', modi, name='modi'),
    
    # 로그인-로그아웃
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # 127.0.0.1:8000/main/...
    re_path(r'^main/', main, name='main'),
]
# 정규 표현식
# [0-9] : 정수값 0 ~ 9 까지 패턴
# [a-z] : 소문자 a ~ z 까지 패턴
# [A-Z] : 대문자 A ~ Z 까지 패턴
# + : 1자리 이상
# {n} : n자리
# {n,m} : n 자리 ~ m 자리 까지
# (...) : () 안에 값을 저장 후 함수의 인자로 전달

myweb/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # 회원가입 공통 질문
    # 이름 / 대표자 이름
    name = models.TextField(max_length=10)
    # employee / employer
    job = models.TextField(max_length=20)
    # 주소
    address = models.TextField(blank=True)
    email = models.TextField(blank=True)
    phonenum=models.TextField(blank=True)
    # 회원가입 개인 질문
    gender = models.TextField(blank=True, default="0")
    date_of_birth=models.TextField(blank=True, default="0000-00-00")
    INTEREST_CHOICES = (
        ('1','디자인'),
        ('2','번역'),
        ('3','연구보조'),
        ('4','프로그래밍')
    )
    interest=models.CharField(max_length=2, choices=INTEREST_CHOICES)
    # 회원가입 기업 질문
    company=models.TextField(blank=True, default="company")

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db.models import Max                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
import random

import sys
sys.path.append("..")
from gonggo.models import Gonggo


# Create your views here.
def mainIndex(request):
    
    data = Gonggo.objects.all().order_by('id')
    return render(request, 'main/index.html',{"gonggo":data})

templates/main/index.html
{% load static %}
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Daepa</title>
    <link rel="shortcut icon" type="image/x-icon"
        href="https://www.lifeplus.co.kr/_resource/_web/images/favicon4.ico?1">
    <link rel="stylesheet" type="text/css" href="https://www.lifeplus.co.kr/_resource/_web/css/common.css">
    <script src="https://connect.facebook.net/signals/config/253252985080421?v=2.9.1&amp;r=stable" async=""></script>
    <script async="" src="https://connect.facebook.net/en_US/fbevents.js"></script>
    <script async="" src="https://www.google-analytics.com/analytics.js"></script>
    <script src="https://www.lifeplus.co.kr/_resource/js/vendor/jquery-1.9.1.min.js"></script>
    <script src="https://www.lifeplus.co.kr/_resource/js/vendor/TweenMax.min.js"></script>
    <script src="https://www.lifeplus.co.kr/_resource/_web/js/common.js"></script>
    <script src="https://www.lifeplus.co.kr/_resource/js/common.js"></script>
    <link type="text/css" href="/static/bs/css/tablemain.css" rel="stylesheet">
    <link type="text/css" href="/static/bs/css/tableutil.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="https://www.lifeplus.co.kr/_resource/_web/css/main.css">
    <script src="https://www.lifeplus.co.kr/_resource/js/vendor/jquery.easeScroll.js"></script>
    <script>
        var rootDomain = "#";
        var resourceDomain = "#";
    </script>

    <link rel="stylesheet" type="text/css" href="{% static 'bs/css/realmain.css' %}">
</head>

<body>
    <div style="text-align:center;">
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALcAAAETCAMAAABDSmfhAAAAA1BMVEUAAACnej3aAAAASElEQVR4nO3BgQAAAADDoPlT3+AEVQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8A8WoAAHxScUAAAAAAElFTkSuQmCC"
            style="width:70%; height:40%;">
        <img src="/static/bs/images/cogi.jpg">
    </div>
    <div id="header">
        <div class="navi" style="top: 0px;">
            <div style="float:left; text-align:left; ">
                <h1>
                    <img src="/static/bs/images/logo1.png" style="width:50px; height:48px; float:left; margin-left:50px;"><span class="ir_text">
                </h1>
            </div>
            <ul class="nav_top">

                

                <div style="float:right;">
                    {% if user.is_authenticated %}
                    <li>
                        <a href="#">
                            <h2>{{ user.profile.name }}님 환영합니다.</h2>
                            <h2>{{user.profile.interest}}</h2>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'modi' %}">
                            <h2>정보수정</h2>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">
                            <h2>로그아웃</h2>
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'reg_account' %}">
                            <h2>회원가입</h2>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'login' %}">
                            <h2>로그인</h2>
                        </a>
                    </li>
                    {% endif %}
                </div>

            </ul>
            <script>
                $('.nowMove').click(function () {
                    localStorage.removeItem('search');
                    localStorage.removeItem('sTop');
                    localStorage.removeItem('page');
                    localStorage.removeItem('order');
                    localStorage.removeItem('value');
                    localStorage.removeItem('back');
                });
            </script>
            <script src="https://www.lifeplus.co.kr/app/blog/sp4/web/js/newsLetter.js" charset="UTF-8"></script>
            <script src="https://www.lifeplus.co.kr/_resource/_web/js/main.js"></script>

        </div>
        <div style="padding: 40px 15% 0;">
            <div style="height: 90px;
            display: block;
            position: relative;
            padding-right: 30px;
            padding-left: 30px;
            width : 1300p100%;
            background: #ED3847;
            border-radius: 3px;">
                <h2 style="color: aliceblue; font-weight:lighter; padding: 30px; 15px ">대학생에게 경험을 주세요!
                    <a href="{% url 'gonggo:form' %}" type="button" style="right: 30px;
            color: #ED3847;
            font-size: 15px;
            font-weight: 600;
            padding: 10px 40px;
            border-radius: 3px;
            background-color: #fff;
            float:right;">공고 등록하기</a></h2>
            </div>
            
            <link type="text/css" href="/static/bs/css/tablemain.css" rel="stylesheet">
            <link type="text/css" href="/static/bs/css/tableutil.css" rel="stylesheet">
                <div class="container-table100"
                    style="background-color: white;  width: 100%; justify-content:initial; max-width:none;">
                    <div class="wrap-table100" style="width:100%; border-radius: 3px">
                        <div class="table">
                            <div class="row header" style="background: #ed3847;">
                                <div class="cell" style="width:50x; margin:10px">
                                    번호
                                </div>
                                <div class="cell">
                                    채용제목
                                </div>
                                <div class="cell">
                                    모집직종
                                </div>
                                <div class="cell">
                                    근무예정지
                                </div>
                            </div>
                            {% for item in gonggo %}
                            <div class="row">
                                <div class="cell" data-title="Full Name">
                                    {{item.id}}
                                </div>
                                <div class="cell" data-title="Age">
                                    {{item.title}}
                                </div>
                                <div class="cell" data-title="Job Title">
                                    {{item.get_interest_display}}
                                </div>
                                <div class="cell" data-title="Location">
                                    {{item.serviceAddr2}}
                                </div>
                            </div>
                            {%endfor%}

                            
        <script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script>
        <script src="vendor/jquery/jquery-3.2.1.min.js" type="text/javascript"></script>

        <script src="vendor/bootstrap/js/popper.js" type="text/javascript"></script>
        <script src="vendor/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>

        <script src="vendor/select2/select2.min.js" type="text/javascript"></script>

        <script src="js/main.js" type="text/javascript"></script>

        <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"
            type="text/javascript"></script>
        <script type="text/javascript">
            window.dataLayer = window.dataLayer || [];
            function gtag() { dataLayer.push(arguments); }
            gtag('js', new Date());

            gtag('config', 'UA-23581568-13');
        </script>

        <br>
        
    
                        </div>
                    </div><a href="{% url 'gonggo:index' %}" style="font-style: bold; font-size: 20; text-align: right;">더 보기</a>
                </div>
            </div>
    


            </div>
        </div>
    </div>
</body>

</html>