board/urls.py
from django.urls import include, re_path
from . import views

app_name='board'
urlpatterns = [
    # 모든 게시물 리스트
    re_path(r'^$', views.mainIndex, name='index'),

    # 특정 게시물(id)의 세부 정보
    re_path(r'^([0-9]+)/$', views.boardDetail, name='detail'),

    # 게시물 추가
    re_path(r'^add/$', views.boardAdd, name='add'),

    # 게시물 수정
    re_path(r'^update/([0-9]+)/$', views.boardUpdate, name='update'),

    # 게시물 삭제
    re_path(r'^delete/([0-9]+)/$', views.boardDelete, name='delete'),

    re_path(r'^updown/$', views.boardLikeHate, name='like_hate'),
]

dict/urls.py
from django.urls import include, re_path
from . import views
app_name='dict'
urlpatterns = (
    re_path(r'^$', views.mainIndex, name='index'),
)

myweb/urls.py
from django.urls import include, re_path, path
from django.contrib import admin
from myweb.views import mainIndex, regAccount, modiAccount, join1, join2, main, modi
from django.contrib.auth import views as auth_views



urlpatterns = [
    # 127.0.0.1:8000/
    re_path(r'^$', mainIndex, name='index'),

    # 127.0.0.1:8000/admin/...
    path('admin/', admin.site.urls),
    re_path(r'^account/register/$', regAccount, name='reg_account'),

    re_path(r'^account/modified/$', modiAccount, name='modi_account'),
    
    re_path(r'^account/register/join1/$', join1, name='join1'),

    re_path(r'^account/register/join2/$', join2, name='join2'),

    # 127.0.0.1:8000/board/...
    re_path(r'^board/', include(r'board.urls')),

    # 127.0.0.1:8000/news/...
    re_path(r'^news/', include(r'news.urls')),

    # 127.0.0.1:8000/webtoon/...
    re_path(r'^webtoon/', include(r'webtoon.urls')),

    # 127.0.0.1:8000/gonggo/...
    re_path(r'^gonggo/', include(r'gonggo.urls')),

    # /error/
    re_path(r'^error/', include(r'error.urls')),

    # 127.0.0.1:8000/modi/...
    re_path(r'^modi/', modi, name='modi'),
    
    # 로그인-로그아웃
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # 127.0.0.1:8000/main/...
    re_path(r'^main/', main, name='main'),
]
# 정규 표현식
# [0-9] : 정수값 0 ~ 9 까지 패턴
# [a-z] : 소문자 a ~ z 까지 패턴
# [A-Z] : 대문자 A ~ Z 까지 패턴
# + : 1자리 이상
# {n} : n자리
# {n,m} : n 자리 ~ m 자리 까지
# (...) : () 안에 값을 저장 후 함수의 인자로 전달

board/models.py
from django.db import models

# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=100)
    author = models.CharField(max_length=50)
    context = models.TextField(default='')
    view_cnt = models.IntegerField(default=0)
    like_cnt = models.IntegerField(default=0)
    hate_cnt = models.IntegerField(default=0)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    no_del = models.BooleanField(default=False)

board/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from board.models import Board

# Create your views here.

def mainIndex(request):
    '''
    게시판 메인 페이지로써 모든 게시물에 대한
    정보를 출력 하기 위한 기능을 가진다.
    게시물 정보 -> id, title, author, view_cnt
    '''

    board = Board.objects.values(
        'id', 'title', 'sub_title', 'author', 'view_cnt').all().order_by('-id')
    data = {
        'board': board
    }
    return render(request, 'board/index.html', data)

def boardDetail(request, idx):
    '''
    게시판 세부 정보 페이지로써 idx에 해당하는
    게시물의 정보를 출력 한다.
    출력 정보 -> id, title, sub_titie, context, view_cnt
                like_cnt, hate_cnt, create_date, update_date
    '''
    try:
        board = Board.objects.get(id=idx)
        board.view_cnt = board.view_cnt + 1
        board.save(update_fields=('view_cnt',))
        data = {
            'board':board
        }
        return render(request, 'board/detail.html', data)
    except Board.DoesNotExist:
        return HttpResponse('해당 페이지가 존재하지 않습니다.')

def boardAdd(request):
    if request.method == 'GET':
        if request.user.is_authenticated():
            data = {
                'action':reverse('board:add'),
                'select_option':[('자유게시판', ), ('연예게시판', ), ('유머게시판', )]
            }
            return render(request, 'board/form.html', data)
        else:
            return redirect('login')
    elif request.method == 'POST':
        if request.user.is_authenticated():
            board = Board()
            board.title = request.POST.get('title')
            board.sub_title = request.POST.get('sub_title')
            board.author = request.user.username
            board.context = request.POST.get('context')
            board.no_del = request.POST.get('no_del', False)
            board.save()

            return redirect('board:detail', board.id)
        else:
            return redirect('login')

def boardUpdate(request, idx):
    if request.method == 'GET':
        try:
            board = Board.objects.get(id=idx)
            data = {
                'action':reverse('board:update', args=(idx,)),
                'select_option':[('자유게시판', ), ('연예게시판', ), ('유머게시판', )],
                'board':board
            }
            return render(request, 'board/form.html', data)
        except Board.DoesNotExist:
            return HttpResponse('해당 페이지가 존재하지 않습니다.')

    elif request.method == 'POST':
        board = Board.objects.get(id=idx)
        board.title = request.POST.get('title')
        board.sub_title = request.POST.get('sub_title')
        board.author = request.POST.get('author')
        board.context = request.POST.get('context')
        board.no_del = request.POST.get('no_del', False)
        board.save(update_fields=('title', 'sub_title', 'author',
            'context', 'no_del', 'update_date'))
        return redirect('board:detail', idx)

def boardDelete(request, idx):
    if Board.objects.values('no_del').get(id=idx)['no_del'] :
        # return HttpResponse('삭제 금지 게시판 입니다. (삭제 불가)')
        return redirect('err:message', 'nodel')
                        # '/error/nodel/'
    else:
        Board.objects.get(id=idx).delete()
    return redirect('board:index')

def boardLikeHate(request):
    if request.user.is_authenticated():
        idx = int(request.GET.get('bid'))
        board = Board.objects.get(id=idx)
        if request.GET.get('like') == 'True':
            board.like_cnt = board.like_cnt + 1
        else:
            board.hate_cnt = board.hate_cnt + 1
        board.view_cnt = board.view_cnt - 1
        board.save(update_fields=('like_cnt', 'hate_cnt', 'view_cnt'))

        return redirect('board:detail', idx)
    else:
        return redirect('err:message', 'noAuth')

templates/board/detail.html
{% extends "index.html" %}
{% block title %}{{ board.title }}{% endblock %}
{% block content %}
<div class="blog-header">
    <div class="container">
        <h1 class="blog-title">{{ board.title }}</h1>
    </div>
</div>
<div class="blog-post">
    <div class="container">
        <p class="blog-post-meta">
            생성일 : {{ board.create_date }}<br>
            수정일 : {{ board.update_date }}<br>
            작성자 : {{ board.author }}
        </p>
        <p>{{ board.context }}</p>
    </div>
</div>
<div class="row text-center">
    <span>
        <button class="btn btn-sm btn-success" type="button" 
        onclick="location.href='{% url 'board:like_hate' %}?like=True&bid={{ board.id }}'">
            추천수 : {{ board.like_cnt }}
        </button>
    </span>
    <span>
        <button class="btn btn-sm btn-danger" type="button" 
        onclick="location.href='{% url 'board:like_hate' %}?like=False&bid={{ board.id }}'">
            비추천수 : {{ board.hate_cnt }}
        </button>
    </span>
</div>
<div class="text-right">
    <div class="row btn-group">
        <button class="btn btn-sm btn-info" type="button" onclick="location.href='{% url 'board:index' %}'">목록</button>
        <button class="btn btn-sm btn-info" type="button" onclick="location.href='{% url 'board:update' board.id %}'">수정</button>
        <button class="btn btn-sm btn-info" type="button" onclick="location.href='{% url 'board:delete' board.id %}'">삭제</button>
    </div>
</div>
{% endblock %}

templates/board/form.html
{% extends "index.html" %}
{% block title %}추가/수정{% endblock %}
{% block content %}
<form action="{{ action }}" method="post">{% csrf_token %}
    <div class="form-group">
        <input class="form-control" type="text" name="title" placeholder="제목" value="{{ board.title }}">
    </div>
    <div class="form-group">
        <select class="form-control" name="sub_title" id="sub_title">
            <option value="자유게시판" id="free">자유게시판</option>
            <option value="연예게시판" id="star">연예게시판</option>
            <option value="유머게시판" id="humo">유머게시판</option>
        </select>
    </div>
    <div class="form-group">
        <input class="form-control" type="text" name="author" placeholder="작성자" value="{{ user.username }}" disabled>
    </div>
    <div class="form-group">
        <textarea class="form-control" name="context">{{ board.context }}</textarea>
    </div>
    <div class="checkbox">
    {% if not board.no_del %}
        <label><input class="form-control" type="checkbox" name="no_del">삭제금지</label>
    {% else %}
        <label><input class="form-control" type="checkbox" name="no_del" checked>삭제금지</label>
    {% endif %}
    </div>
    <div class="row text-right">
        <button class="btn btn-success" type="submit">전송</button>
    </div>
</form>
{% endblock %}

templates/board/index.html
{% extends "index.html" %}
{% block title %}게시판 리스트{% endblock %}
{% block content %}
<div class="row">
    {% if user.is_authenticated %}
        <button class="btn btn-default btn-sm"
        onclick="location.href='{% url 'board:add' %}'">추가</button>
    {% else %}
        <button class="btn btn-default btn-sm"
        onclick="location.href='{% url 'login' %}'">추가</button>
    {% endif %}
</div>
<div class="row">
    <table class="table table-hover">
        <tr>
            <th class="col-md-1 text-center">번호</th>
            <th class="col-md-2 text-center">종류</th>
            <th class="col-md-6 text-center">제목</th>
            <th class="col-md-2 text-center">작성자</th>
            <th class="col-md-1 text-center">조회수</th>
        </tr>
        {% for item in board %}
            <tr>
                <td class="col-md-1 text-center">{{ item.id }}</td>
                <td class="col-md-2 text-center">{{ item.sub_title }}</td>
                <td class="col-md-6"><a href="{% url 'board:detail' item.id %}">{{ item.title }}</a></td>
                <td class="col-md-2 text-center">{{ item.author }}</td>
                <td class="col-md-1 text-center">{{ item.view_cnt }}</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}